[package]
name = "stody1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"

[profile.dev.package."*"]
opt-level = 3
#런타임 동안 감시하지 말고 바로 수행하라 렉 방지